input.onButtonEvent(Button.A, input.buttonEventClick(), function () {
    strip.setBrightness(2500)
    strip.showRainbow(1, 360)
    strip.show()
    basic.pause(5000)
    strip.clear()
    strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(4, neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(5, neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(6, neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(7, neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(8, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(9, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(10, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(11, neopixel.colors(NeoPixelColors.Green))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(12, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(13, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(14, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(15, neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(16, neopixel.colors(NeoPixelColors.Violet))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(17, neopixel.colors(NeoPixelColors.Violet))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(18, neopixel.colors(NeoPixelColors.Violet))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(19, neopixel.colors(NeoPixelColors.Violet))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(20, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(21, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(22, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(23, neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(24, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(25, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(26, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(27, neopixel.colors(NeoPixelColors.White))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(28, neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    strip.setPixelColor(29, neopixel.colors(NeoPixelColors.Yellow))
    strip.show()
    basic.pause(50)
    strip.setPixelColor(30, neopixel.colors(NeoPixelColors.Red))
    strip.show()
    basic.pause(50)
    basic.pause(50)
    for (let index = 0; index < 4; index++) {
        strip.showColor(neopixel.colors(NeoPixelColors.Red))
        basic.pause(1000)
        strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
        basic.pause(1000)
    }
})
input.onButtonEvent(Button.B, input.buttonEventClick(), function () {
	
})
let strip: neopixel.Strip = null
strip = neopixel.create(DigitalPin.P0, 30, NeoPixelMode.RGB)
strip.showRainbow(1, 360)
strip.show()
basic.pause(5000)
strip.clear()
for (let index = 0; index < 1; index++) {
    music.setVolume(255)
    music.play(music.stringPlayable("F G E G B F G D ", 180), music.PlaybackMode.InBackground)
    strip.setBrightness(2000)
    strip.showColor(neopixel.colors(NeoPixelColors.Red))
    basic.pause(500)
    strip.show()
    strip.clear()
    strip.showColor(neopixel.colors(NeoPixelColors.Orange))
    strip.show()
    basic.pause(500)
    strip.clear()
    strip.showColor(neopixel.colors(NeoPixelColors.Green))
    strip.show()
    basic.pause(500)
    strip.clear()
    strip.showColor(neopixel.colors(NeoPixelColors.Blue))
    strip.show()
    music.play(music.stringPlayable("F G E G B F G D ", 180), music.PlaybackMode.InBackground)
    basic.pause(500)
    strip.clear()
    strip.showColor(neopixel.colors(NeoPixelColors.Indigo))
    strip.show()
    basic.pause(500)
    strip.clear()
    strip.showColor(neopixel.colors(NeoPixelColors.Purple))
    strip.show()
    basic.pause(500)
    strip.clear()
}
strip.setBrightness(3000)
strip.showColor(neopixel.colors(NeoPixelColors.White))
strip.show()
basic.pause(10000000)
strip.clear()
